---
title: "GGplot Practice"
format: html
editor: visual
---

## 

```{r}
library(tidyverse)
library(here)
library(janitor)
library(dplyr)
library(ggplot2)
# essentials visualization (data, (aes)thetics, (geom)etry)
```

```{r}
#read in the lizards

lizards <- read_csv(here("data_tidy", "lizards.csv"))

# most common, recommended
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point()
# second, more flexible
ggplot(data = lizards) +
  geom_point(aes(x = total_length, y = weight))

# third, most flexible
ggplot() +
  geom_point(data = lizards, aes(x = total_length, y = weight))
```

```{r}
#not good
ggplot(data = lizards,
       aes(x = total_length, y = weight)) +
  geom_line()
```

```{r}
ggplot(data = lizards, aes(x = total_length)) +
  geom_histogram()
```

```{r}
ggplot(data = lizards, aes (y = common_name, x = weight)) + 
  geom_jitter()
```

```{r}
#aestehtic mapping coolor.co for better palletes
ggplot(data = lizards, aes(x = weight)) +
  geom_histogram(color = "orange",
                 fill = "purple",
                 size = 2, 
                 linetype = "dotted")

```

```{r}
ggplot(data = lizards, aes(x = total_length, y = weight)) +
  geom_point(color = "cyan4", 
             fill = "yellow2",
             shape = 22,
             size = 3,
             alpha = 0.4)
```

```{r}
# asesthetic graphing
ggplot(data = lizards,
       aes(x = total_length, y = weight)) +
  geom_point(aes(color = common_name),
               alpha = 0.3)
```

```{r}
# Themes
ggplot(data = lizards, aes(x = site, y = weight)) +
  geom_jitter(aes(color = common_name)) +
  theme_minimal() + 
  theme(plot.title = element_text(hjust = 0.5)) +
  labs(x = "Total length (mm)",
       y = "Weight (grams)",
       title = "Lizard Size")

# update access labels
```

```{r}
#reorder data
lizard_counts <- lizards %>%
  count(common_name)

ggplot(data = lizard_counts,
       aes(y = fct_reorder(common_name, n), x = n)) +
  geom_col() +
  labs(x = "Individuals (n)",
       y = "Species common name")
```



